### ISSUE TITLE
Not connecting to mongodb

### ISSUE THREAD

**Issue by samppita** [watson-developer-cloud/your-celebrity-match#83]
Hi, 

I deployed the app on Bluemix, changed the credentials for personality insights & twitter. 
Created a database and a user in mlab and changed the line in config.js using the connection to my mlab database:

```
 FROM THIS: mongodb: process.env.MONGODB || 'mongodb://localhost/celebs',
 TO THIS: mongodb: process.env.MONGODB || 'mongodb://<myuser>:<mypassword>@ds036617.mlab.com:36617/celebrities',
```
I have access to my database using mongo shell. 
 mongo ds036617.mlab.com:36617/celebrities -u <dbuser> -p <dbpassword> 

When I try to do npm start I get an error:
```
connect-to-mongodb
Server running on port: 3000
(node:1453) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
mongoose-connection-error: { MongoError: Authentication failed.
    at Function.MongoError.create (/Users/sandra/Desktop/Bluemix/Projects/your-celebrity-match/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/sandra/Desktop/Bluemix/Projects/your-celebrity-match/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/sandra/Desktop/Bluemix/Projects/your-celebrity-match/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/sandra/Desktop/Bluemix/Projects/your-celebrity-match/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/sandra/Desktop/Bluemix/Projects/your-celebrity-match/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed' }
```

Is there anything else I need to change to use the mongodb in mLab??? 

Thanks!

**Comment by nfriedly** [comment]
I'm not sure; double-check your credentials - the actual error is `MongoError: Authentication failed.`
